version: '3'
name: nacos-cluster
services: 
  nacos1:
    container_name: nacos-server01
    hostname: nacos-server01
    image: nacos/nacos-server:2.0.2
    environment: 
      - MODE=cluster
      - PREFER_HOST_MODE=hostname
      - NACOS_SERVERS=nacos-server01:8848 nacos-server02:8848 nacos-server03:8848
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=10.10.10.10
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=123456
      - MYSQL_SERVICE_DB_NAME=nacos_config
      - JVM_XMS=128m
      - JVM_XMX=128m
      - JVM_XMN=128m
    networks:
      - mysql
    volumes: 
      - /usr/mwt/nacos/server01/config:/home/nacos/config
      - /usr/mwt/nacos/server01/data:/home/nacos/data
      - /usr/mwt/nacos/server01/logs:/home/nacos/logs
    ports: 
      - 8846:8848
      - 9555:9555
    restart: always
  nacos2:
    container_name: nacos-server02
    hostname: nacos-server02
    image: nacos/nacos-server:2.0.2
    environment: 
      - MODE=cluster
      - PREFER_HOST_MODE=hostname
      - NACOS_SERVERS=nacos-server01:8848 nacos-server02:8848 nacos-server03:8848
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=10.10.10.10
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=123456
      - MYSQL_SERVICE_DB_NAME=nacos_config
      - JVM_XMS=128m
      - JVM_XMX=128m
      - JVM_XMN=128m
    networks:
      - mysql
    volumes: 
      - /usr/mwt/nacos/server02/config:/home/nacos/config
      - /usr/mwt/nacos/server02/data:/home/nacos/data
      - /usr/mwt/nacos/server02/logs:/home/nacos/logs
    ports: 
      - 8847:8848
    restart: always
  nacos3:
    container_name: nacos-server03
    hostname: nacos-server03
    image: nacos/nacos-server:2.0.2
    environment: 
      - MODE=cluster
      - PREFER_HOST_MODE=hostname
      - NACOS_SERVERS=nacos-server01:8848 nacos-server02:8848 nacos-server03:8848
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=10.10.10.10
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=123456
      - MYSQL_SERVICE_DB_NAME=nacos_config
      - JVM_XMS=128m
      - JVM_XMX=128m
      - JVM_XMN=128m
    networks:
      - mysql
    volumes: 
      - /usr/mwt/nacos/server03/config:/home/nacos/config
      - /usr/mwt/nacos/server03/data:/home/nacos/data
      - /usr/mwt/nacos/server03/logs:/home/nacos/logs
    ports: 
      - 8848:8848
    restart: always
networks:
  mysql:
    external:
      name: mysql-cluster_mysql