version: '2'
name: elk-cluster
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    environment: 
      - "xpack.security.enabled=false"
      - "discovery.type=single-node"
    volumes:
      - /usr/mwt/elk/data:/usr/share/elasticsearch/data
      - /usr/mwt/elk/plugins:/usr/share/elasticsearch/plugins
    container_name: es
    hostname: elasticsearch
    restart: always
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elk
  kibana:
    image: docker.elastic.co/kibana/kibana:7.8.0
    environment:
      I18N_LOCALE: zh-CN
    container_name: kibana
    hostname: kibana
    restart: always
    ports:
      - "5601:5601"
    networks:
      - elk 
    depends_on:
      - elasticsearch
networks:
  elk:
    driver: bridge
